services:
  - type: web
    name: icu-deterioration-dashboard
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install streamlit plotly pandas requests numpy
    startCommand: streamlit run dashboard/app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: FOG_URL
        value: http://34.207.149.53:8000
      - key: PYTHON_VERSION
        value: 3.11.0